"""added calls table

Revision ID: 49fea01b18d2
Revises: 1faf85a861c6
Create Date: 2024-09-07 06:49:05.829768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fea01b18d2'
down_revision: Union[str, None] = '1faf85a861c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.Date(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('is_call_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
