"""call members funcationlity

Revision ID: 5f8adf906022
Revises: 2ba41eda113c
Create Date: 2024-09-23 11:03:20.162946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8adf906022'
down_revision: Union[str, None] = '2ba41eda113c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_members',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('call_id', 'user_id')
    )
    op.create_index(op.f('ix_call_members_call_id'), 'call_members', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_members_user_id'), 'call_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_members_user_id'), table_name='call_members')
    op.drop_index(op.f('ix_call_members_call_id'), table_name='call_members')
    op.drop_table('call_members')
    # ### end Alembic commands ###
